### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by zorion79** [umputun/dkll#15]
I hate panic!

I run service in docker swarm. Mongo 4.2 Mongo started.

```
docker-logger_server.1.svglcz9oc3ng@docker-desktop    | 2022/03/14 16:37:56.562 [DEBUG] {cmd/server.go:53 cmd.ServerCmd.Run} server mode activated --
docker-logger_server.1.svglcz9oc3ng@docker-desktop    | 2022/03/14 16:37:56.562 [INFO]  {cmd/server.go:122 cmd.ServerCmd.makeWriters} backup files location /srv/logs
docker-logger_server.1.svglcz9oc3ng@docker-desktop    | 2022/03/14 16:37:56.562 [DEBUG] {cmd/server.go:97 cmd.makeMongoClient} make mongo client for "mongodb://admin:pass@mongo:27017"
docker-logger_server.1.svglcz9oc3ng@docker-desktop    | panic: interface conversion: interface {} is nil, not string
```

Where is from panic?

**Comment by zorion79** [comment]
This compose file panic with same error

```yml
version: '2'

volumes:
  mongo:
    external: false

services:
  dkll-server:
    build: .
    image: umputun/dkll
    container_name: "dkll-server"
    hostname: "dkll-server"
    restart: always

    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - MONGO=mongodb://mongo:27017
      - MONGO_DELAY=5s
      - BACK_LOG=/srv/logs
      - MONGO_PASSWD=${MONGO_PASSWD:-pass}
      - APP_UID=1001  # change to your local UID
      - TIME_ZONE=UTC # change to desired TZ, i.e. "America/Chicago"

    ports:
      - 8080:8080
      - 514:5514

    volumes:
      - mongo:/srv/logs

    command: ["/srv/dkll", "server"]

  mongo:
    image: mongo:4.2
    hostname: mongo
    restart: always
    logging: *default_logging
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWD:-pass}
    ports:
      - "27017:27017"
```

**Comment by umputun** [comment]
the reason is the legacy documentation I have not updated during migration to mongo-driver. The `MONGO` param is the connection url as you figured, but it includes `db` and `collection` parameters. 

I have updated compose examples, the readme and also added a check to fail better in this case.

**Comment by zorion79** [comment]
Mongo 4.2
Still error

```log
dkll-server            | 2022/03/14 20:08:54.242 [DEBUG] {cmd/server.go:97 cmd.makeMongoClient} make mongo client for "mongodb://mongo:27017?db=dkll&collecion=logs"
dkll-server            | 2022/03/14 20:08:54.242 [ERROR] {app/main.go:69 main.main} server failed, can't make mongo client: can't connect to mongo mongodb://mongo:27017?db=dkll&collecion=logs: failed to connect mongo: error parsing uri: must have a / before the query ?
```

**Comment by umputun** [comment]
> mongo URL specify the standard [mongodb connection string](https://docs.mongodb.com/manual/reference/connection-string/) with db and collection extra parameters, e.g. mongodb://localhost:27017/admin?db=dkll&collection=logs

**Comment by zorion79** [comment]
db not found?
![image](https://user-images.githubusercontent.com/2866872/158271263-3ed285e9-9128-4178-b90b-25348c281c4b.png)

**Comment by umputun** [comment]
not sure what exactly you are showing and how you translated it to "db not found". The` zhs: no matches` message has nothing to do with mongo.

you can just `mongosh mongodb://127.0.0.1:27017` and `show dbs` inside the mongo shell.

**Comment by zorion79** [comment]
Maybe update docker image?

## Very simple compose file

```yml
version: '2'

services:
  dkll-server:
    build: .
    image: umputun/dkll
    container_name: "dkll-server"
    hostname: "dkll-server"
    restart: always

    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - DEBUG=true
      - MONGO=mongodb://mongo:27017/dkll?collections=logs
      - MONGO_DELAY=5s
      - BACK_LOG=/srv/logs
      - MONGO_PASSWD=pass
      - APP_UID=1001  # change to your local UID
      - TIME_ZONE=Asia/Vladivostok # change to desired TZ, i.e. "America/Chicago"

    ports:
      - 8080:8080
      - 514:5514

    command: ["/srv/dkll", "server"]

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    logging: *default_logging
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
```

## Run

```bash
docker system prune --force && docker volume prune --force && docker network prune --force
docker-compose -f compose-server.yml up
```

## Same Error

```log
mongo_1        | {"t":{"$date":"2022-03-15T00:41:39.946+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
mongo_1        | {"t":{"$date":"2022-03-15T00:41:39.946+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
mongo_1        | {"t":{"$date":"2022-03-15T00:41:40.406+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.160.3:37082","uuid":"074770ad-8600-4a15-a951-12d39532ecee","connectionId":1,"connectionCount":1}}
mongo_1        | {"t":{"$date":"2022-03-15T00:41:40.406+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"192.168.160.3:37082","client":"conn1","doc":{"driver":{"name":"mongo-go-driver","version":"v1.8.1"},"os":{"type":"linux","architecture":"amd64"},"platform":"go1.17.5","application":{"name":"dkll-server"}}}}
mongo_1        | {"t":{"$date":"2022-03-15T00:41:40.407+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.160.3:37084","uuid":"5f97a053-c94d-4547-b897-93c10617f086","connectionId":2,"connectionCount":2}}
mongo_1        | {"t":{"$date":"2022-03-15T00:41:40.408+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"192.168.160.3:37084","client":"conn2","doc":{"driver":{"name":"mongo-go-driver","version":"v1.8.1"},"os":{"type":"linux","architecture":"amd64"},"platform":"go1.17.5","application":{"name":"dkll-server"}}}}
dkll-server    | panic: interface conversion: interface {} is nil, not string
dkll-server    |
dkll-server    | goroutine 1 [running]:
dkll-server    | github.com/umputun/dkll/app/cmd.ServerCmd.Run({{0x1f90, 0x158a, {0xc000024086, 0x2b}, 0x12a05f200, 0x2540be400, 0x2faf080, {0xc000028021, 0x9}, 0x0, ...}, ...}, ...)
dkll-server    |        /build/dkll/app/cmd/server.go:65 +0x6f5
dkll-server    | main.main()
dkll-server    |        /build/dkll/app/main.go:68 +0x59f
mongo_1        | {"t":{"$date":"2022-03-15T00:41:40.411+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn1","msg":"Interrupted operation as its client disconnected","attr":{"opId":19}}
```

**Comment by zorion79** [comment]
New question. How hide pass from mongo URL?

## This isn't working.

```
mongodb://mongo:27017/admin?db=dkll&collection=logs
```

```log
dkll-server    | init container
dkll-server    | set timezone Asia/Vladivostok (Tue Mar 15 11:37:23 +10 2022)
dkll-server    | custom APP_UID not defined, using default uid=1001
dkll-server    | execute "/srv/dkll server"
dkll-server    | dkll server master-8599167-20220314T03:22:35
dkll-server    | 2022/03/15 11:37:23.902 [DEBUG] {cmd/server.go:53 cmd.ServerCmd.Run} server mode activated master-8599167-20220314T03:22:35
dkll-server    | 2022/03/15 11:37:23.902 [INFO]  {cmd/server.go:128 cmd.ServerCmd.makeWriters} backup files location /srv/logs
dkll-server    | 2022/03/15 11:37:23.902 [DEBUG] {cmd/server.go:103 cmd.makeMongoClient} make mongo client for "mongodb://mongo:27017/admin?db=dkll&collection=logs"
dkll-server    | 2022/03/15 11:37:23.908 [INFO]  {server/mongo.go:56 server.NewMongo} make new mongo server with {MaxDocs:50000000 MaxCollectionSize:10000000000 Delay:0s DBName:dkll Collection:logs}
dkll-server    | 2022/03/15 11:37:23.908 [INFO]  {server/mongo.go:221 server.(*Mongo).init} create Collection logs
dkll-server    | 2022/03/15 11:37:23.908 [ERROR] {app/main.go:69 main.main} server failed, initilize collection logs with {MaxDocs:50000000 MaxCollectionSize:10000000000 Delay:0s DBName:dkll Collection:logs}: (Unauthorized) command create requires authentication
dkll-server    | 2022/03/15 11:37:23.908 [ERROR] {app/main.go:69 main.main} server failed, initilize collection logs with {MaxDocs:50000000 MaxCollectionSize:10000000000 Delay:0s DBName:dkll Collection:logs}: (Unauthorized) command create requires authentication
```
## This is working

```yml
version: '2'

services:
  dkll-server:
    build: .
    image: umputun/dkll:master
    container_name: "dkll-server"
    hostname: "dkll-server"
    restart: always

    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - DEBUG=true
      - MONGO=mongodb://admin:pass@mongo:27017/admin?db=dkll&collection=logs
      - MONGO_DELAY=5s
      - BACK_LOG=/srv/logs
      - MONGO_PASSWD=pass
      - APP_UID=1001  # change to your local UID
      - TIME_ZONE=Asia/Vladivostok # change to desired TZ, i.e. "America/Chicago"

    ports:
      - 8080:8080
      - 514:5514

    command: ["/srv/dkll", "server"]

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    logging: *default_logging
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
```
